### ISSUE TITLE
Can initial state be one large object instead of an array?

### ISSUE THREAD

**Issue by denny64** [msteckyefantis/reduxx#1]

**Comment by msteckyefantis** [comment]
Hello Denny,

Yes an object based `initialState` input format was going to be my next update.

Using regular objects wouldn't work (because it gets confusing if you want to set a value as an object).

So I am thinking of making the alternate input format along the lines of this:
```.js
'use strict';

const ReduxX = require( 'reduxx' );

const { s, empty } = ReduxX;


module.exports = ReduxX({

    initialState: {
        
        monkey: s(
            
            'donkeyKong',        

            {
                favoriteFood: s( 'banana' )
            }    
        ),

        hippo: s(

            empty,
            
            {
                mood: s( 'hungry' )
            }
        ),   
    }
});
```

I haven't fully thought it through but I will figure it out and add it on the weekend. Please let me know if you have any suggestions as to how you might solve this.

Thanks for bringing up this issue.👍

**Comment by msteckyefantis** [comment]
You can now set the initial state using an object:

[Documentation on Object Form for Initial State](https://github.com/msteckyefantis/reduxx#object-form-for-initial-state)
