### ISSUE TITLE
Can't use reduxx node_module with create-react-app

### ISSUE THREAD

**Issue by xrendan** [msteckyefantis/reduxx#5]
When trying to make a production build I get an error failing to minify reduxx: `Failed to minify the code from this file: ./node_modules/reduxx/lib/tools.js:7`

You can see the create-react-app explanation [here](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

My current workaround is to simply have the git build in my src directory but that doesn't make sense long term.

**Comment by msteckyefantis** [comment]
Hello Mr. Samek,

Thanks for bringing this up, I will try to have this figured out by the end of the week.

**Comment by xrendan** [comment]
Lovely, thanks! And thanks for developing the library ??
________________________________

**Comment by msteckyefantis** [comment]
I am happy that others find my library helpful😄.

Try ReduxX v13. I made it so that the npm package only contains a bundled javascript file that contains ReduxX.

[![Screen_Shot_2018-08-03_at_9.48.41_PM.png](https://s33.postimg.cc/yjjo44gfz/Screen_Shot_2018-08-03_at_9.48.41_PM.png)]

I am using [Parcel Js](https://github.com/parcel-bundler/parcel) for the bundling.

The actual module should work exactly the same as before.

Try it out and if you can please let me know if this works for you and if you have any other suggestions for ReduxX. Thanks again for your suggestion.

**Comment by xrendan** [comment]
I just upgraded to v13 and its working great! Thanks so much for developing reduxx 😊

You can check out what I've built with reduxx at yegsecrets.ca if you want!
________________________________

**Comment by msteckyefantis** [comment]
sick website🇨🇦🇨🇦🇨🇦🇨🇦!
